//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkbdbwebapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studentid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> genderid { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string emailid { get; set; }
        public string location { get; set; }
    }

    public bool insertstudentbyEF(studentinsertrequest studentrequest,ref string Errormessage)
    {
        bool result = false;
        try
        {
            using(project1Entities p1e=new project1Entities())
            {
                student record = new student();
                record.studentid = studentrequest.studentid;
                record.firstname = studentrequest.firstname;
                record.lastname = studentrequest.lastname;
                record.genderid = Convert.ToByte(studentrequest.genderid);
                record.DOB = Convert.ToDateTime(studentrequest.DOB.ToString());
                record.emailid = studentrequest.emailid;
                record.location = studentrequest.location;
                project1Entities.student.add(record);
                project1Entities.save
              
            }
        }
    }
}
